<?php

function state_poll_menu()
{
    $items = array();
    $items['state_poll'] = array(
            'title' => 'Ice Cream Tracker',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('state_poll_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
    );

    $items['state_poll_result'] = array(
            'title' => 'Poll Results:',
            'page callback' => 'state_poll_result',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
    );
    return $items;
}

function state_poll_form()
{
    $form['state'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#description' => 'What US State do you live in? Please us the following formats:"\n"
                            "Xxxxx," "XX," "xx," or "xxxxx."',
        '#element_validate' => array('letter_validate'),
        '#required' => TRUE,
    );

    $form['icecream'] = array(
        '#title' => 'Ice Cream',
        '#type' => 'textfield',
        '#description' => 'What\s your favorite ice cream?',
        // '#element_validate' => array('custom'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit your answer',
    );
    return $form;
}

function letter_validate($element)
{
    $temp = $element['#value'];
    $len = strlen($temp);
    drupal_set_message($temp);

    if($len < 2){
        form_error($element, "Please enter a valid format");

    } else if($len == 2){

        if($temp == strtoupper($temp)){
            return;
        }else if(strtolower($temp) == $temp){
            return;
        } else {
            form_error($element, "Please enter a valid format");
        }

    } else if($len > 2){

        if(strtoupper(substr($temp, 0, 1)) == substr($temp, 0, 1)){
            if(strtolower(substr($temp, 1, $len - 1)) != substr($temp, 1, $len - 1)){
                form_error($element, "Please enter a valid format");
            }
        }else if(strtolower($temp) != $temp){
            form_error($element, "Please enter a valid format");
        }
    } // end if len > 2


    // if(strtoupper($temp) != $temp && strlen($temp) == 2){
    //     form_error($element, "Please enter a valid format.");
    // }
}
