<?php

    function rock_paper_scissors_menu()
    {
        $items = array();
        $items['rock_paper_scissors'] = array(
            'title' => 'Rock Paper Scissors',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('rock_paper_scissors_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['player_1_page'] = array(
            'title' => 'Game Results',
            'page callback' => 'game_winner',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function rock_paper_scissors_form()
    {
        $form['player_1'] = array(
            '#title' => 'Player 1',
            '#type' => 'select',

        );
    }

//RPS Logic
    <?php
    class Game
    {
        private $user;
        private $comp;
        function setUser($user) {
            $this->user = (string) $new_user;
        }
        function getUser() {
            return $this->user;
        }
        function makeGame($user, $comp, $is_random)
        {
            //$is_random = true;
           if ($is_random) {
                $comp_number = rand(1, 3);
                if ($comp_number == 1) {
                    $comp = "rock";
                } elseif ($comp_number == 2) {
                    $comp = "paper";
                } elseif ($comp_number == 3) {
                    $comp = "scissors";
                }
            }
        //    var_dump($comp);
            if ($user == "rock" && $comp == "paper") {
                return "You lose.";
            } elseif ($user == "scissors" && $comp == "rock"){
                return "You lose.";
            } elseif ($user == "paper" && $comp == "scissors"){
                return "You lose.";
            } elseif ($user == "rock" && $comp == "scissors") {
                return "You win!";
            } elseif ($user == "scissors" && $comp == "paper") {
                return "You win!";
            } elseif ($user == "paper" && $comp == "rock") {
                return "You win!";
            } elseif ($user = $comp) {
                return "It's a tie!";
            }
        }
    }
?>
